[[plugins]]
repo = 'Shougo/deoplete.nvim'
	hook_add = '''
		let g:deoplete#enable_at_startup = 1
		let g:deoplete#enable_ignore_case = 1
	'''

[[plugins]]
repo = 'zchee/deoplete-clang'
	hook_source = '''
		let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-10/lib/libclang-10.so.1'
		let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
	'''
on_ft = ['c', 'cpp', 'cmake']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
	" 補完してくれる
    let g:ale_completion_enabled = 1
    " エラー行に表示するマーク
    let g:ale_sign_error = '⨉'
    let g:ale_sign_warning = '⚠'
	" C++
    let g:ale_linters = {
        \   'c' : ['clangd'],
        \   'cpp' : ['clangd']
    \}
'''
